const images = {
    logo: require('./logo.png'),
    coin: require('./coin.png'),
    add: require('./add.png'),
    mobile: require('./mobile.png'),
    search: require('./search.png'),
    chat: require('./chat.png'),
    avatar: require('./avatar.png'),
    chPlayIcon: require('./ch-play-icon.png'),
    appStoreIcon: require('./app-store-icon.png'),
    qr: require('./qr.png'),
    id: require('./id.png'),
    banner: require('./bg-banner.jpg'),
    edit: require('./edit.png'),
    girl: require('./girl.png'),
    boy: require('./boy.png'),
    lgGirl: require('./lg-girl.png'),
    lgBoy: require('./lg-boy.png'),
    chatEmo: require('./chat-emo.png'),
    player: require('./player.png'),
    follow: require('./follow.png'),
    following: require('./following.png'),
    bunnySad: require('./bunny-sad.gif'),
};

export default images;
