export {default as Home} from './Home/Home'
export {default as PostsNew} from './Posts/PostsNew'
export {default as PostsFollowing} from './Posts/PostsFollowing'
export {default as SkillPage} from './SkillPage/SkillPage'
export {default as Account} from './Account/Account'
export {default as ErrorPage} from './ErrorPage/ErrorPage'
export {default as UserDetail} from './UserDetail/UserDetail'