export { default as Header } from './layouts/Header/Header';
export { default as HeaderMobile } from './layouts/Header/HeaderMobile';
export { default as Footer } from './layouts/Footer/Footer';
export { default as FooterMobile } from './layouts/Footer/FooterMobile';
export { default as Games } from './layouts/Sidebar/Games';
export { default as Root } from './layouts/Root/Root';
export { default as RootMobile } from './layouts/Root/RootMobile';
export { default as LoadingIcon } from './Loading/LoadingIcon';
export { default as SidebarItem } from './SidebarItem';
export { default as InfiniteScroll} from './InfiniteScroll';
export { default as ViewImage} from './ViewImage';
export { default as PageAnimate} from './PageAnimate';
export { default as PrivatePage } from './PrivatePage';
export { default as PostSidebar } from './layouts/Sidebar/PostSidebar';
export { default as DefaultLayout } from './layouts/DefaultLayout/DefaultLayout';
export { default as PostsMobileLayout } from './layouts/PostsMobileLayout/PostsMobileLayout';
